=== jenshnielsen/Qcodes/qcodes/config/qcodesrc_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type" : "object",
    "description": "schema for a qcodes config file",
    "properties":{
        "core" : {
            "description": "controls core settings of qcodes",
            "type" : "object",
            "properties" : {
                "default_fmt": {
                    "type" : "string",
                    "description": "default location formatter",
                    "default": "data/{date}/#{counter}_{name}_{time}"
                },
                "loglevel" :{
                    "type" : "string",
                    "description": "control logging  level",
                    "default": "DEBUG",
                    "enum" : [
                        "CRITICAL",
                        "ERROR",
                        "WARNING",
                        "INFO",
                        "DEBUG"
                    ]
                }
            },
            "required":["loglevel" ]
        },
        "gui" : {
            "type" : "object",
            "description": "controls gui of qcodes",
            "properties" : {
                "notebook": {
                    "description": "Use notebook frontend",
                    "type" : "boolean",
                    "default": true
                },
                "plotlib": {
                    "description": "Plotting library",
                    "type": "string",
                    "enum": ["QT", "matplotlib" ],
                    "default": "matplotlib"
                }
            },
            "required":[ "notebook", "plotlib" ]
        },
        "fridgeserver" : {
            "type" : "object",
            "description": "controls Triton fridge server settings",
            "properties" : {
                "htppport" : {
                    "description": "Port to use for http communication",
                    "type": "integer",
                    "default": 8000
                },
                "wsport" : {
                    "description": "Port to use for Websocket communication",
                    "type": "integer",
                    "default": 8765
                },
                "wsserver" : {
                    "description": "Websocket endpoint to connect to",
                    "type": "string",
                    "default": "ws://localhost"
                },
                "wssendinterval" : {
                    "description": "Time to wait (in sec) between sending websocket data",
                    "type": "number",
                    "default": 1.0
                },
                "wsconnectinterval" : {
                    "description": "Time to wait (in sec) between between attempting to reconnect to ws server",
                    "type": "number",
                    "default": 10.0
                },
                "usemocktriton" : {
                    "description": "Use a mock Triton to emulate connections",
                    "type": "boolean",
                    "default": false
                },
                "tritonaddress" : {
                    "description": "Address of the triton to communicate with",
                    "type": "string",
                    "default": "http://localhost"
                },
                "tritonname" : {
                    "description": "Instrument name to use for Triton",
                    "type": "string",
                    "default": "Triton"
                }
            }
        },
        "user":{
            "type" : "object",
            "description": "controls user settings of qcodes",
            "properties" : {}
        }
       },
    "required":[ "gui", "core" , "user"]
}

=== jenshnielsen/Qcodes/qcodes/config/qcodesrc.json
{
    "core":{
        "loglevel": "DEBUG",
        "default_fmt": "data/{date}/#{counter}_{name}_{time}"
    },
    "gui" :{
        "notebook": true,
        "plotlib": "matplotlib"
    },
    "fridgeserver": {
        "wsport": 8765,
        "wsenableport": 8766,
        "wsserver": "ws://localhost",
        "httpport": 8000,
        "wssendinterval": 1.0,
        "wsconnectinterval": 10.0,
        "tritonaddress": "localhost",
        "usemocktriton": false,
        "tritonname": "Triton"
    },
    "user": {}
}
